version: '3'
services:

  db:
    image: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210

  # cs-dbm:
  #   build: ../aggregation-dbm
  #   depends_on:
  #     - db
  #   ports:
  #     - "8002:8002"
  #   environment:
  #     COM_COUCHBASE_DBHOST: db
  #     COM_COUCHBASE_USER: Administrator
  #     COM_COUCHBASE_PWORD: password

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "PruOneProposalProcessTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  # consumer:
  #   build: ../stream-consumer-all
  #   environment:
  #     KAFKA_HOST:  kafka
  #     KAFKA_PORTS: '9092' #pass comma delimited string for array value 
  #     ENABLE_SNAPPY_COMPRESSION: 'false'
  #     KAFKA_GROUP_ID: generic_group_1
  #     DEFAULT_TOPIC: 'ServiceTopic' #pass comma delimited string for array value 
  #     CORE_HOSTNAME: agg-core
  #     CORE_PORT: 3000
  #     UPDATE_PATH: /api/post/data
      
  dl-pruone-ing:
    build: .
    container_name: consumer
    ports:
      - "3000:3000"
    environment:
      KAFKA_HOST:  kafka
      KAFKA_PORTS: '9092' #pass comma delimited string for array value 
      ENABLE_SNAPPY_COMPRESSION: 'false'
      KAFKA_GROUP_ID: main-group
      DEFAULT_TOPIC: 'PruOneProposalProcessTopic' #pass comma delimited string for array value 
      DBM_HOSTNAME: cs-dbm
      DBM_PORT: 8002
      UPSERT_PATH: /api/cb/upsert
      GETBYID_PATH: /api/cb/getByKey
      AGG_DATA_BUCKET: pruone-data
      COM_COUCHBASE_DBHOST: db
      CS_PUB_URL: http://rest-dummy:3001
    depends_on:
      - kafka

  kafkacat:
    container_name: kafkacat
    image: confluentinc/cp-kafkacat
    volumes:
         - d:/temp:/temp
    command: tail -f /dev/null
  
  rest-dummy:
    build: ../rest-dummy
    container_name: rest-dummy
    ports:
      - "3001:3001"

  
 
